# This is a config for E2B sandbox template.
# You can use template ID (d6vdbrttr94ee6ehncq6) or template name (viber-nextjs-Anjan-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("viber-nextjs-Anjan-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("viber-nextjs-Anjan-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('viber-nextjs-Anjan-test')

team_id = "cc4a6de6-4b0f-462c-8eb3-54a10a70b053"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "viber-nextjs-Anjan-test"
template_id = "d6vdbrttr94ee6ehncq6"
